export const PermissionWildcard = '*'

export const PermissionMembersView = 'members.view'
export const PermissionMembersInvite = 'members.invite'
export const PermissionMembersManage = 'members.manage'
export const PermissionMembersRemove = 'members.remove'

export const PermissionOrgOwner = 'org.owner'
export const PermissionOrgAdmin = 'org.admin'
export const PermissionOrganizationsView = 'organizations.view'
export const PermissionOrganizationsCreate = 'organizations.create'
export const PermissionRolesView = 'roles.view'
export const PermissionUsersView = 'users.view'

export const PermissionSettingsView = 'settings.view'
export const PermissionSettingsWrite = 'settings.write'
export const PermissionEnvironmentsView = 'environments.view'
export const PermissionEnvironmentsWrite = 'environments.write'
export const PermissionSecretsView = 'secrets.view'
export const PermissionSecretsWrite = 'secrets.write'
export const PermissionVariablesView = 'variables.view'
export const PermissionVariablesWrite = 'variables.write'
export const PermissionProvidersView = 'providers.view'
export const PermissionProvidersWrite = 'providers.write'
